### ISSUE TITLE
2.5 Application: Secret Sharing - first claim to show why cannot reconstruct f(0) with fewer than k points

### ISSUE THREAD

**Issue by aa84** [pim-book/exercises#11]
Regarding the following sentence at page 26: "Moreover, for each choice of _y_ you get a _different_ interpolating polynomial (this is due to Theorem 2.3)". 

Why is this due to Theorem 2.3 (zero polynomial) and not to Theorem 2.2? I can't find any reference to the zero polynomial in the first claim. 
For the Theorem 2.2, given a list of d + 1 points and choosing the _y_ of one of those points don't we just get a different input list that generates a different interpolating polynomial?

**Comment by j2kun** [comment]
Absolutely right! I'll add this to the fixes for the upcoming second edition.
