### ISSUE TITLE
2.3 Existence & Uniqueness - Why is the Twin Prime example a uniqueness question?

### ISSUE THREAD

**Issue by ddadon10** [pim-book/exercises#18]
In the second edition of the book, in section 2.3, page 14, there is the following introduction to Existence proofs:

> First, a word about existence and uniqueness. Existence proofs are classic in mathematics. They come in all shapes and sizes. Mathematicians like to take interesting properties they see on small objects, write down the property in general, and then ask things like, “Are there arbitrarily large objects with this property?” or, “Are there infinitely many objects with this property?” I imagine a similar pattern in physics. Given equations that govern the internal workings of a star you might ask, would these equations support arbitrarily massive stars?

Then right below, there is the following paragraphe about the Twin Prime:

> One simple uniqueness question is quite famous: are there are infinitely many pairs of prime numbers of the form p, p + 2? For example, 11 and 13 work, but 23 is not part of such a pair. It’s an open question whether there are infinitely many such pairs. The assertion that there are is called the Twin Prime Conjecture.

Why is the Twin Prime an uniqueness question? 
I would think this is an existence question because we are looking to know if there is "infinitely many pairs".

**Comment by j2kun** [comment]
You're right. That is just an editing oversight :)

Good examples of existence and uniqueness problems include many basic theorems in the study of differential equations, where there is a unique function that satisfies a given differential equation and initial value choice, such as https://en.wikipedia.org/wiki/Picard%E2%80%93Lindel%C3%B6f_theorem

Another uniqueness theorem example is the uniqueness of prime factorizations https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic

**Comment by ddadon10** [comment]
All good, thank you very much for your clear and fast answer

I really enjoy reading your book, that is great work 🙏
