### ISSUE TITLE
Chapter 14 - Global param gradient for Linear Node

### ISSUE THREAD

**Issue by suryabulusu** [pim-book/exercises#5]
What is wrong with the following code for compute_global_param_gradient -- 
```python
def compute_global_param_grad(self):
        # dE/dw_i = dE/df*df/dw_i 
        return [
            self.global_grad * self.local_param_grad[i]
            for i in range(arglen))
        ]
```

**Comment by j2kun** [comment]
Nothing, I think. The difference between your code and mine is organizational, not mathematical.

In my code, the argument node queries the dependent node for its local gradient during backpropagation (see local_gradient_for_argument), and the argument node just passes "self." The argument node doesn't know which index the dependent node associates with itself, as it shouldn't: that would leak abstraction. Also, the dependent node keeps references to all its argument nodes, so it can ask them for their output. So it made sense to me to organize the bookkeeping around argument references, and keep a dictionary mapping the argument reference to the index of the actual parameter associated with it.
