### ISSUE TITLE
Ex 2.1.3 how much of a proof can be implied?

### ISSUE THREAD

**Issue by ghost** [pim-book/exercises#7]
By definition n and m are the largest degree in each respective polynomial, which means the the terms `a_nx^n` and `b_mx^m` are the the largest terms of each respective polynomial, so the largest the degree will be is `(a_nx^n )(b_mx^m)` or `a_nb_mx^(n + m)`. How can I show that these are the largest, is there a step in relation to the previous question?

**Comment by j2kun** [comment]
You can be more formal if you want by writing down the generic form of a polynomial and doing the multiplication (using a summation notation or ellipses for the implied pattern). The only thing to prove is that no other terms in the product can also have an exponent of `n+m` (or else there is the risk of two terms summing to zero), and that `a_n b_m` is not zero.

But it seems you have a clear understanding of the behavior here; I wouldn't sweat it too much.

**Comment by ghost** [comment]
Thank you! I am enjoying the book so far but I feel like my pace is a bit slow, is the intention for all the exercises to be completed before moving on, or are they there so you can review topics later?

**Comment by j2kun** [comment]
I wouldn't say they're mandatory at all. The earlier exercises are supposed to be the easiest, and the later exercises are supposed to be hard, though some readers have pointed out I've put some unexpectedly difficult exercises early in the book. What can I say, I'm a first-time author. So don't feel bad if you get stuck :)
